[2024-11-26T22:06:03.149+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T22:06:03.169+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_sheet_to_s3_to_rds.load_to_mysql manual__2024-11-26T22:05:48.402475+00:00 [queued]>
[2024-11-26T22:06:03.179+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_sheet_to_s3_to_rds.load_to_mysql manual__2024-11-26T22:05:48.402475+00:00 [queued]>
[2024-11-26T22:06:03.179+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-26T22:06:03.192+0000] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): load_to_mysql> on 2024-11-26 22:05:48.402475+00:00
[2024-11-26T22:06:03.197+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5018) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-26T22:06:03.199+0000] {standard_task_runner.py:72} INFO - Started process 5020 to run task
[2024-11-26T22:06:03.199+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_sheet_to_s3_to_rds', 'load_to_mysql', 'manual__2024-11-26T22:05:48.402475+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/google_sheet_to_s3_to_rds.py', '--cfg-path', '/tmp/tmpg8k2179i']
[2024-11-26T22:06:03.200+0000] {standard_task_runner.py:105} INFO - Job 170: Subtask load_to_mysql
[2024-11-26T22:06:03.243+0000] {task_command.py:467} INFO - Running <TaskInstance: google_sheet_to_s3_to_rds.load_to_mysql manual__2024-11-26T22:05:48.402475+00:00 [running]> on host 4b3a7f9b2751
[2024-11-26T22:06:03.551+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_sheet_to_s3_to_rds' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T22:05:48.402475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T22:05:48.402475+00:00'
[2024-11-26T22:06:03.552+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-26T22:06:03.553+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-26T22:06:03.553+0000] {logging_mixin.py:190} INFO - Current task name:load_to_mysql state:running start_date:2024-11-26 22:06:03.170404+00:00
[2024-11-26T22:06:03.553+0000] {logging_mixin.py:190} INFO - Dag name:google_sheet_to_s3_to_rds and current dag run status:running
[2024-11-26T22:06:03.554+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T22:06:03.554+0000] {sql.py:278} INFO - Executing: 
            LOAD DATA INFILE '/tmp/DMMlkp.csv'
            INTO TABLE stage.dmm_lookup
            FIELDS TERMINATED BY ',' 
            LINES TERMINATED BY '
'
            IGNORE 1 LINES
            (Score, Stage, Data, Enterprise, Leadership, Targets, Technology, Analytics);
        
[2024-11-26T22:06:03.565+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2024-11-26T22:06:03.571+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2024-11-26T22:06:03.870+0000] {sql.py:544} INFO - Running statement: 
            LOAD DATA INFILE '/tmp/DMMlkp.csv'
            INTO TABLE stage.dmm_lookup
            FIELDS TERMINATED BY ',' 
            LINES TERMINATED BY '
'
            IGNORE 1 LINES
            (Score, Stage, Data, Enterprise, Leadership, Targets, Technology, Analytics);
        , parameters: None
[2024-11-26T22:06:03.916+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1045, "Access denied for user 'apacheadmin'@'%' (using password: YES)")
[2024-11-26T22:06:03.927+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-26T22:06:03.928+0000] {logging_mixin.py:190} INFO - Task start:2024-11-26 22:06:03.170404+00:00 end:2024-11-26 22:06:03.927079+00:00 duration:0.756675
[2024-11-26T22:06:03.928+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): load_to_mysql> dag:<DAG: google_sheet_to_s3_to_rds> dagrun:<DagRun google_sheet_to_s3_to_rds @ 2024-11-26 22:05:48.402475+00:00: manual__2024-11-26T22:05:48.402475+00:00, state:running, queued_at: 2024-11-26 22:05:48.411392+00:00. externally triggered: True>
[2024-11-26T22:06:03.928+0000] {logging_mixin.py:190} INFO - Failure caused by (1045, "Access denied for user 'apacheadmin'@'%' (using password: YES)")
[2024-11-26T22:06:03.929+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=google_sheet_to_s3_to_rds, task_id=load_to_mysql, run_id=manual__2024-11-26T22:05:48.402475+00:00, execution_date=20241126T220548, start_date=20241126T220603, end_date=20241126T220603
[2024-11-26T22:06:03.943+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T22:06:03.943+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 170 for task load_to_mysql ((1045, "Access denied for user 'apacheadmin'@'%' (using password: YES)"); 5020)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1045, "Access denied for user 'apacheadmin'@'%' (using password: YES)")
[2024-11-26T22:06:03.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-26T22:06:03.991+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T22:06:03.994+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
