[2024-11-26T16:43:07.244+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T16:43:07.260+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_dag.upload_to_s3 manual__2024-11-26T16:43:03.620319+00:00 [queued]>
[2024-11-26T16:43:07.268+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_dag.upload_to_s3 manual__2024-11-26T16:43:03.620319+00:00 [queued]>
[2024-11-26T16:43:07.269+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-26T16:43:07.284+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-11-26 16:43:03.620319+00:00
[2024-11-26T16:43:07.290+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=495) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-26T16:43:07.292+0000] {standard_task_runner.py:72} INFO - Started process 497 to run task
[2024-11-26T16:43:07.292+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_dag', 'upload_to_s3', 'manual__2024-11-26T16:43:03.620319+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload.py', '--cfg-path', '/tmp/tmph6dybpi9']
[2024-11-26T16:43:07.293+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask upload_to_s3
[2024-11-26T16:43:07.337+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_dag.upload_to_s3 manual__2024-11-26T16:43:03.620319+00:00 [running]> on host 4b3a7f9b2751
[2024-11-26T16:43:07.411+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_dag' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T16:43:03.620319+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T16:43:03.620319+00:00'
[2024-11-26T16:43:07.413+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-26T16:43:07.413+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-26T16:43:07.414+0000] {logging_mixin.py:190} INFO - Current task name:upload_to_s3 state:running start_date:2024-11-26 16:43:07.261713+00:00
[2024-11-26T16:43:07.414+0000] {logging_mixin.py:190} INFO - Dag name:s3_dag and current dag run status:running
[2024-11-26T16:43:07.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T16:43:07.424+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2024-11-26T16:43:07.425+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-11-26T16:43:08.338+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/s3_upload.py", line 11, in upload_to_s3
    hook.load_file(filename=filename, key=key, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 155, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 129, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1112, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
    return transfer.upload_file(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/transfer.py", line 372, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 265, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 589, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
    self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/utils.py", line 254, in get_file_size
    return os.path.getsize(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Andrew/GitHub/how-agile-airflow/data/DMMlkp.csv'
[2024-11-26T16:43:08.348+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-26T16:43:08.349+0000] {logging_mixin.py:190} INFO - Task start:2024-11-26 16:43:07.261713+00:00 end:2024-11-26 16:43:08.348561+00:00 duration:1.086848
[2024-11-26T16:43:08.350+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): upload_to_s3> dag:<DAG: s3_dag> dagrun:<DagRun s3_dag @ 2024-11-26 16:43:03.620319+00:00: manual__2024-11-26T16:43:03.620319+00:00, state:running, queued_at: 2024-11-26 16:43:03.629523+00:00. externally triggered: True>
[2024-11-26T16:43:08.350+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:/Users/Andrew/GitHub/how-agile-***/data/DMMlkp.csv'
[2024-11-26T16:43:08.351+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=s3_dag, task_id=upload_to_s3, run_id=manual__2024-11-26T16:43:03.620319+00:00, execution_date=20241126T164303, start_date=20241126T164307, end_date=20241126T164308
[2024-11-26T16:43:08.365+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T16:43:08.366+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 92 for task upload_to_s3 ([Errno 2] No such file or directory: 'C:/Users/Andrew/GitHub/how-agile-airflow/data/DMMlkp.csv'; 497)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/s3_upload.py", line 11, in upload_to_s3
    hook.load_file(filename=filename, key=key, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 155, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 129, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1112, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
    return transfer.upload_file(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/transfer.py", line 372, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 265, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 589, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
    self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/utils.py", line 254, in get_file_size
    return os.path.getsize(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 62, in getsize
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Andrew/GitHub/how-agile-airflow/data/DMMlkp.csv'
[2024-11-26T16:43:08.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-26T16:43:08.459+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T16:43:08.463+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
