[2024-12-06T03:05:45.816+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T03:05:45.833+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: firestore_to_s3_to_rds.exec_fact_load manual__2024-12-06T03:05:26.764725+00:00 [queued]>
[2024-12-06T03:05:45.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: firestore_to_s3_to_rds.exec_fact_load manual__2024-12-06T03:05:26.764725+00:00 [queued]>
[2024-12-06T03:05:45.842+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T03:05:45.856+0000] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): exec_fact_load> on 2024-12-06 03:05:26.764725+00:00
[2024-12-06T03:05:45.863+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4678) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T03:05:45.865+0000] {standard_task_runner.py:72} INFO - Started process 4680 to run task
[2024-12-06T03:05:45.865+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'firestore_to_s3_to_rds', 'exec_fact_load', 'manual__2024-12-06T03:05:26.764725+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/firebase_to_s3_to_rds.py', '--cfg-path', '/tmp/tmpmxti6gzq']
[2024-12-06T03:05:45.866+0000] {standard_task_runner.py:105} INFO - Job 242: Subtask exec_fact_load
[2024-12-06T03:05:45.909+0000] {task_command.py:467} INFO - Running <TaskInstance: firestore_to_s3_to_rds.exec_fact_load manual__2024-12-06T03:05:26.764725+00:00 [running]> on host 4b3a7f9b2751
[2024-12-06T03:05:46.214+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='firestore_to_s3_to_rds' AIRFLOW_CTX_TASK_ID='exec_fact_load' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T03:05:26.764725+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T03:05:26.764725+00:00'
[2024-12-06T03:05:46.215+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T03:05:46.216+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T03:05:46.216+0000] {logging_mixin.py:190} INFO - Current task name:exec_fact_load state:running start_date:2024-12-06 03:05:45.834693+00:00
[2024-12-06T03:05:46.217+0000] {logging_mixin.py:190} INFO - Dag name:firestore_to_s3_to_rds and current dag run status:running
[2024-12-06T03:05:46.217+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T03:05:46.218+0000] {sql.py:278} INFO - Executing: EXEC dbo.update_user_fact;
[2024-12-06T03:05:46.226+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2024-12-06T03:05:46.234+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2024-12-06T03:05:46.449+0000] {sql.py:544} INFO - Running statement: EXEC dbo.update_user_fact;, parameters: None
[2024-12-06T03:05:46.494+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXEC dbo.update_user_fact' at line 1")
[2024-12-06T03:05:46.524+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T03:05:46.525+0000] {logging_mixin.py:190} INFO - Task start:2024-12-06 03:05:45.834693+00:00 end:2024-12-06 03:05:46.523712+00:00 duration:0.689019
[2024-12-06T03:05:46.527+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): exec_fact_load> dag:<DAG: firestore_to_s3_to_rds> dagrun:<DagRun firestore_to_s3_to_rds @ 2024-12-06 03:05:26.764725+00:00: manual__2024-12-06T03:05:26.764725+00:00, state:running, queued_at: 2024-12-06 03:05:26.773706+00:00. externally triggered: True>
[2024-12-06T03:05:46.528+0000] {logging_mixin.py:190} INFO - Failure caused by (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXEC dbo.update_user_fact' at line 1")
[2024-12-06T03:05:46.530+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=firestore_to_s3_to_rds, task_id=exec_fact_load, run_id=manual__2024-12-06T03:05:26.764725+00:00, execution_date=20241206T030526, start_date=20241206T030545, end_date=20241206T030546
[2024-12-06T03:05:46.560+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T03:05:46.562+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 242 for task exec_fact_load ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXEC dbo.update_user_fact' at line 1"); 4680)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXEC dbo.update_user_fact' at line 1")
[2024-12-06T03:05:46.602+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T03:05:46.626+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T03:05:46.632+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
