[2024-11-27T02:01:24.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-27T02:01:24.026+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_firebase_s3.google_sheet_data_to_s3 scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T02:01:24.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_firebase_s3.google_sheet_data_to_s3 scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T02:01:24.042+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-27T02:01:24.062+0000] {taskinstance.py:2889} INFO - Executing <Task(GoogleApiToS3Operator): google_sheet_data_to_s3> on 2024-11-26 00:00:00+00:00
[2024-11-27T02:01:24.069+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-27T02:01:24.071+0000] {standard_task_runner.py:72} INFO - Started process 5620 to run task
[2024-11-27T02:01:24.072+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_firebase_s3', 'google_sheet_data_to_s3', 'scheduled__2024-11-26T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/google_firebase_s3.py', '--cfg-path', '/tmp/tmpd4kdcz_u']
[2024-11-27T02:01:24.074+0000] {standard_task_runner.py:105} INFO - Job 172: Subtask google_sheet_data_to_s3
[2024-11-27T02:01:24.137+0000] {task_command.py:467} INFO - Running <TaskInstance: google_firebase_s3.google_sheet_data_to_s3 scheduled__2024-11-26T00:00:00+00:00 [running]> on host 4b3a7f9b2751
[2024-11-27T02:01:24.248+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_firebase_s3' AIRFLOW_CTX_TASK_ID='google_sheet_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T00:00:00+00:00'
[2024-11-27T02:01:24.252+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-27T02:01:24.252+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-27T02:01:24.254+0000] {logging_mixin.py:190} INFO - Current task name:google_sheet_data_to_s3 state:running start_date:2024-11-27 02:01:24.027124+00:00
[2024-11-27T02:01:24.254+0000] {logging_mixin.py:190} INFO - Dag name:google_firebase_s3 and current dag run status:running
[2024-11-27T02:01:24.255+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-27T02:01:24.255+0000] {google_api_to_s3.py:142} INFO - Transferring data from sheets to s3
[2024-11-27T02:01:24.268+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-27T02:01:24.272+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-11-27T02:01:24.273+0000] {discovery_api.py:74} INFO - Authenticating Google API Client
[2024-11-27T02:01:25.346+0000] {http.py:140} WARNING - Encountered 403 Forbidden with reason "PERMISSION_DENIED"
[2024-11-27T02:01:25.352+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 147, in execute
    data = self._retrieve_data_from_google_api()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 161, in _retrieve_data_from_google_api
    return google_discovery_api_hook.query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 102, in query
    api_response = self._call_api_request(google_api_conn_client, endpoint, data, paginate, num_retries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 117, in _call_api_request
    return google_api_endpoint_instance.execute(num_retries=num_retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-ESRUZvSKfI3F5d0f0IqMc78KNOw8YGL3PWR_NuJd-k/values/Sheet1?alt=json returned "Request had insufficient authentication scopes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_SCOPE_INSUFFICIENT', 'domain': 'googleapis.com', 'metadata': {'service': 'sheets.googleapis.com', 'method': 'google.apps.sheets.v4.SpreadsheetsService.GetValues'}}]">
[2024-11-27T02:01:25.382+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-27T02:01:25.384+0000] {logging_mixin.py:190} INFO - Task start:2024-11-27 02:01:24.027124+00:00 end:2024-11-27 02:01:25.381742+00:00 duration:1.354618
[2024-11-27T02:01:25.384+0000] {logging_mixin.py:190} INFO - Task:<Task(GoogleApiToS3Operator): google_sheet_data_to_s3> dag:<DAG: google_firebase_s3> dagrun:<DagRun google_firebase_s3 @ 2024-11-26 00:00:00+00:00: scheduled__2024-11-26T00:00:00+00:00, state:running, queued_at: 2024-11-27 02:01:16.200125+00:00. externally triggered: False>
[2024-11-27T02:01:25.385+0000] {logging_mixin.py:190} INFO - Failure caused by <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-ESRUZvSKfI3F5d0f0IqMc78KNOw8YGL3PWR_NuJd-k/values/Sheet1?alt=json returned "Request had insufficient authentication scopes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_SCOPE_INSUFFICIENT', 'domain': 'googleapis.com', 'metadata': {'service': 'sheets.googleapis.com', 'method': 'google.apps.sheets.v4.SpreadsheetsService.GetValues'}}]">
[2024-11-27T02:01:25.386+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=google_firebase_s3, task_id=google_sheet_data_to_s3, run_id=scheduled__2024-11-26T00:00:00+00:00, execution_date=20241126T000000, start_date=20241127T020124, end_date=20241127T020125
[2024-11-27T02:01:25.459+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-27T02:01:25.461+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 172 for task google_sheet_data_to_s3 (<HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-ESRUZvSKfI3F5d0f0IqMc78KNOw8YGL3PWR_NuJd-k/values/Sheet1?alt=json returned "Request had insufficient authentication scopes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_SCOPE_INSUFFICIENT', 'domain': 'googleapis.com', 'metadata': {'service': 'sheets.googleapis.com', 'method': 'google.apps.sheets.v4.SpreadsheetsService.GetValues'}}]">; 5620)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 147, in execute
    data = self._retrieve_data_from_google_api()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 161, in _retrieve_data_from_google_api
    return google_discovery_api_hook.query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 102, in query
    api_response = self._call_api_request(google_api_conn_client, endpoint, data, paginate, num_retries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 117, in _call_api_request
    return google_api_endpoint_instance.execute(num_retries=num_retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-ESRUZvSKfI3F5d0f0IqMc78KNOw8YGL3PWR_NuJd-k/values/Sheet1?alt=json returned "Request had insufficient authentication scopes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'ACCESS_TOKEN_SCOPE_INSUFFICIENT', 'domain': 'googleapis.com', 'metadata': {'service': 'sheets.googleapis.com', 'method': 'google.apps.sheets.v4.SpreadsheetsService.GetValues'}}]">
[2024-11-27T02:01:25.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-27T02:01:25.533+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T02:01:25.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
