[2024-12-06T02:57:27.229+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T02:57:27.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: firestore_to_s3_to_rds.read_s3_file_into_string scheduled__2024-12-05T00:00:00+00:00 [queued]>
[2024-12-06T02:57:27.257+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: firestore_to_s3_to_rds.read_s3_file_into_string scheduled__2024-12-05T00:00:00+00:00 [queued]>
[2024-12-06T02:57:27.371+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T02:57:28.671+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): read_s3_file_into_string> on 2024-12-05 00:00:00+00:00
[2024-12-06T02:57:28.677+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T02:57:28.678+0000] {standard_task_runner.py:72} INFO - Started process 4543 to run task
[2024-12-06T02:57:28.679+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'firestore_to_s3_to_rds', 'read_s3_file_into_string', 'scheduled__2024-12-05T00:00:00+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/firebase_to_s3_to_rds.py', '--cfg-path', '/tmp/tmpuxrupas9']
[2024-12-06T02:57:28.680+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask read_s3_file_into_string
[2024-12-06T02:57:28.890+0000] {task_command.py:467} INFO - Running <TaskInstance: firestore_to_s3_to_rds.read_s3_file_into_string scheduled__2024-12-05T00:00:00+00:00 [running]> on host 4b3a7f9b2751
[2024-12-06T02:57:29.821+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='firestore_to_s3_to_rds' AIRFLOW_CTX_TASK_ID='read_s3_file_into_string' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-05T00:00:00+00:00'
[2024-12-06T02:57:29.822+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T02:57:29.823+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T02:57:29.823+0000] {logging_mixin.py:190} INFO - Current task name:read_s3_file_into_string state:running start_date:2024-12-06 02:57:27.249049+00:00
[2024-12-06T02:57:29.823+0000] {logging_mixin.py:190} INFO - Dag name:firestore_to_s3_to_rds and current dag run status:running
[2024-12-06T02:57:29.824+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T02:57:29.833+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2024-12-06T02:57:29.834+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 94, in read_s3_file_into_string
    s3_client = boto3.client(
                ^^^^^
NameError: name 'boto3' is not defined. Did you mean: 'bool'?
[2024-12-06T02:57:29.848+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T02:57:29.848+0000] {logging_mixin.py:190} INFO - Task start:2024-12-06 02:57:27.249049+00:00 end:2024-12-06 02:57:29.847984+00:00 duration:2.598935
[2024-12-06T02:57:29.849+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): read_s3_file_into_string> dag:<DAG: firestore_to_s3_to_rds> dagrun:<DagRun firestore_to_s3_to_rds @ 2024-12-05 00:00:00+00:00: scheduled__2024-12-05T00:00:00+00:00, state:running, queued_at: 2024-12-06 02:56:59.916022+00:00. externally triggered: False>
[2024-12-06T02:57:29.850+0000] {logging_mixin.py:190} INFO - Failure caused by name 'boto3' is not defined
[2024-12-06T02:57:29.851+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=firestore_to_s3_to_rds, task_id=read_s3_file_into_string, run_id=scheduled__2024-12-05T00:00:00+00:00, execution_date=20241205T000000, start_date=20241206T025727, end_date=20241206T025729
[2024-12-06T02:57:30.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T02:57:30.893+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 235 for task read_s3_file_into_string (name 'boto3' is not defined; 4543)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/firebase_to_s3_to_rds.py", line 94, in read_s3_file_into_string
    s3_client = boto3.client(
                ^^^^^
NameError: name 'boto3' is not defined. Did you mean: 'bool'?
[2024-12-06T02:57:30.942+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T02:57:30.951+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
