[2024-11-25T17:53:26.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T17:53:26.088+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_firebase_s3.google_sheet_data_to_s3 manual__2024-11-25T17:48:22.190315+00:00 [queued]>
[2024-11-25T17:53:26.100+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_firebase_s3.google_sheet_data_to_s3 manual__2024-11-25T17:48:22.190315+00:00 [queued]>
[2024-11-25T17:53:26.101+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-25T17:53:26.124+0000] {taskinstance.py:2889} INFO - Executing <Task(GoogleApiToS3Operator): google_sheet_data_to_s3> on 2024-11-25 17:48:22.190315+00:00
[2024-11-25T17:53:26.140+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1954) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-25T17:53:26.142+0000] {standard_task_runner.py:72} INFO - Started process 1956 to run task
[2024-11-25T17:53:26.143+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_firebase_s3', 'google_sheet_data_to_s3', 'manual__2024-11-25T17:48:22.190315+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/google_firebase_s3.py', '--cfg-path', '/tmp/tmplj1tz5ng']
[2024-11-25T17:53:26.144+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask google_sheet_data_to_s3
[2024-11-25T17:53:26.187+0000] {task_command.py:467} INFO - Running <TaskInstance: google_firebase_s3.google_sheet_data_to_s3 manual__2024-11-25T17:48:22.190315+00:00 [running]> on host 4b3a7f9b2751
[2024-11-25T17:53:26.267+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_firebase_s3' AIRFLOW_CTX_TASK_ID='google_sheet_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T17:48:22.190315+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T17:48:22.190315+00:00'
[2024-11-25T17:53:26.268+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-25T17:53:26.269+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-25T17:53:26.269+0000] {logging_mixin.py:190} INFO - Current task name:google_sheet_data_to_s3 state:running start_date:2024-11-25 17:53:26.089596+00:00
[2024-11-25T17:53:26.270+0000] {logging_mixin.py:190} INFO - Dag name:google_firebase_s3 and current dag run status:running
[2024-11-25T17:53:26.270+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T17:53:26.271+0000] {google_api_to_s3.py:142} INFO - Transferring data from sheets to s3
[2024-11-25T17:53:26.279+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-25T17:53:26.283+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-11-25T17:53:26.284+0000] {discovery_api.py:74} INFO - Authenticating Google API Client
[2024-11-25T17:53:26.293+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 147, in execute
    data = self._retrieve_data_from_google_api()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 161, in _retrieve_data_from_google_api
    return google_discovery_api_hook.query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 100, in query
    google_api_conn_client = self.get_conn()
                             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 77, in get_conn
    http_authorized = self._authorize()
                      ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 405, in _authorize
    credentials = self.get_credentials()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 363, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 335, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 224, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-11-25T17:53:26.297+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-25T17:53:26.298+0000] {logging_mixin.py:190} INFO - Task start:2024-11-25 17:53:26.089596+00:00 end:2024-11-25 17:53:26.297246+00:00 duration:0.20765
[2024-11-25T17:53:26.299+0000] {logging_mixin.py:190} INFO - Task:<Task(GoogleApiToS3Operator): google_sheet_data_to_s3> dag:<DAG: google_firebase_s3> dagrun:<DagRun google_firebase_s3 @ 2024-11-25 17:48:22.190315+00:00: manual__2024-11-25T17:48:22.190315+00:00, state:running, queued_at: 2024-11-25 17:48:22.199888+00:00. externally triggered: True>
[2024-11-25T17:53:26.299+0000] {logging_mixin.py:190} INFO - Failure caused by The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-11-25T17:53:26.300+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=google_firebase_s3, task_id=google_sheet_data_to_s3, run_id=manual__2024-11-25T17:48:22.190315+00:00, execution_date=20241125T174822, start_date=20241125T175326, end_date=20241125T175326
[2024-11-25T17:53:26.310+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T17:53:26.311+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task google_sheet_data_to_s3 (The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 1956)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 147, in execute
    data = self._retrieve_data_from_google_api()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/google_api_to_s3.py", line 161, in _retrieve_data_from_google_api
    return google_discovery_api_hook.query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 100, in query
    google_api_conn_client = self.get_conn()
                             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/discovery_api.py", line 77, in get_conn
    http_authorized = self._authorize()
                      ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 405, in _authorize
    credentials = self.get_credentials()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 363, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 335, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 411, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 224, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-11-25T17:53:26.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-25T17:53:26.375+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T17:53:26.379+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
