[2024-11-26T20:28:12.958+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T20:28:12.975+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_sheet_to_s3_to_rds.load_to_mysql manual__2024-11-26T20:28:00.947809+00:00 [queued]>
[2024-11-26T20:28:12.983+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_sheet_to_s3_to_rds.load_to_mysql manual__2024-11-26T20:28:00.947809+00:00 [queued]>
[2024-11-26T20:28:12.983+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-26T20:28:12.998+0000] {taskinstance.py:2889} INFO - Executing <Task(S3ToMySqlOperator): load_to_mysql> on 2024-11-26 20:28:00.947809+00:00
[2024-11-26T20:28:13.005+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3493) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-26T20:28:13.006+0000] {standard_task_runner.py:72} INFO - Started process 3495 to run task
[2024-11-26T20:28:13.007+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_sheet_to_s3_to_rds', 'load_to_mysql', 'manual__2024-11-26T20:28:00.947809+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/google_sheet_to_s3_to_rds.py', '--cfg-path', '/tmp/tmp41tb07_i']
[2024-11-26T20:28:13.008+0000] {standard_task_runner.py:105} INFO - Job 113: Subtask load_to_mysql
[2024-11-26T20:28:13.052+0000] {task_command.py:467} INFO - Running <TaskInstance: google_sheet_to_s3_to_rds.load_to_mysql manual__2024-11-26T20:28:00.947809+00:00 [running]> on host 4b3a7f9b2751
[2024-11-26T20:28:13.298+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_sheet_to_s3_to_rds' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T20:28:00.947809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T20:28:00.947809+00:00'
[2024-11-26T20:28:13.299+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-26T20:28:13.300+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-26T20:28:13.300+0000] {logging_mixin.py:190} INFO - Current task name:load_to_mysql state:running start_date:2024-11-26 20:28:12.976212+00:00
[2024-11-26T20:28:13.301+0000] {logging_mixin.py:190} INFO - Dag name:google_sheet_to_s3_to_rds and current dag run status:running
[2024-11-26T20:28:13.302+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T20:28:13.302+0000] {s3_to_mysql.py:82} INFO - Loading DMMlkp.csv to MySql table stage.dmm_lookup...
[2024-11-26T20:28:13.311+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2024-11-26T20:28:13.312+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-11-26T20:28:13.312+0000] {s3.py:1419} INFO - Downloading source S3 file from Bucket None with path DMMlkp.csv
[2024-11-26T20:28:13.462+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/transfers/s3_to_mysql.py", line 85, in execute
    file = s3_hook.download_file(key=self.s3_source_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 155, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 129, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1422, in download_file
    s3_obj = self.get_key(key, bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 155, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 129, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 961, in get_key
    obj = self.resource.Object(bucket_name, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/resources/factory.py", line 528, in create_resource
    return partial(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/resources/base.py", line 123, in __init__
    raise ValueError(f'Required parameter {identifier} not set')
ValueError: Required parameter bucket_name not set
[2024-11-26T20:28:13.474+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-26T20:28:13.475+0000] {logging_mixin.py:190} INFO - Task start:2024-11-26 20:28:12.976212+00:00 end:2024-11-26 20:28:13.474398+00:00 duration:0.498186
[2024-11-26T20:28:13.476+0000] {logging_mixin.py:190} INFO - Task:<Task(S3ToMySqlOperator): load_to_mysql> dag:<DAG: google_sheet_to_s3_to_rds> dagrun:<DagRun google_sheet_to_s3_to_rds @ 2024-11-26 20:28:00.947809+00:00: manual__2024-11-26T20:28:00.947809+00:00, state:running, queued_at: 2024-11-26 20:28:00.970338+00:00. externally triggered: True>
[2024-11-26T20:28:13.476+0000] {logging_mixin.py:190} INFO - Failure caused by Required parameter bucket_name not set
[2024-11-26T20:28:13.477+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=google_sheet_to_s3_to_rds, task_id=load_to_mysql, run_id=manual__2024-11-26T20:28:00.947809+00:00, execution_date=20241126T202800, start_date=20241126T202812, end_date=20241126T202813
[2024-11-26T20:28:13.489+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T20:28:13.490+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 113 for task load_to_mysql (Required parameter bucket_name not set; 3495)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/transfers/s3_to_mysql.py", line 85, in execute
    file = s3_hook.download_file(key=self.s3_source_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 155, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 129, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1422, in download_file
    s3_obj = self.get_key(key, bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 155, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 129, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 961, in get_key
    obj = self.resource.Object(bucket_name, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/resources/factory.py", line 528, in create_resource
    return partial(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/resources/base.py", line 123, in __init__
    raise ValueError(f'Required parameter {identifier} not set')
ValueError: Required parameter bucket_name not set
[2024-11-26T20:28:13.542+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-26T20:28:13.560+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T20:28:13.562+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
